// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220726180611_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Entities.Venda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ALTERADO_POR_USU_ID")
                        .HasColumnType("int");

                    b.Property<int>("CRIADO_POR_USU_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DAT_ALTERACAO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DAT_CRIACAO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DAT_EXCLUSAO")
                        .HasColumnType("datetime2");

                    b.Property<int>("EXCLUIDO_POR_USU_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IND_ATIVO")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
