CREATE TABLE USUARIO(
ID int PRIMARY KEY NOT NULL,
NOME varchar(255),
DAT_NASCIMENTO date,
DAT_CRIACAO date,
DAT_ALTERACAO date,
DAT_EXCLUSAO date,
CRIADO_POR_USU_ID int,
ALTERADO_POR_USU_ID int, 
EXCLUIDO_POR_USU_ID int,
IND_ATIVO char
);

CREATE TABLE PRODUTOS(
ID int PRIMARY KEY NOT NULL,
USUARIO_ID int,
NOME varchar (255),
VALOR decimal,
DAT_CRIACAO date,
DAT_ALTERACAO date,
DAT_EXCLUSAO date,
CRIADO_POR_USU_ID int,
ALTERADO_POR_USU_ID int,
EXCLUIDO_POR_USU_ID int,
IND_ATIVO char,
CONSTRAINT FK_PRODUTOUSUARIO FOREIGN KEY (USUARIO_ID)
REFERENCES USUARIO(ID));


CREATE TABLE ESTOQUE(
ID int PRIMARY KEY NOT NULL,
ID_PRODUTO int,
NM_QUANTIDADE int,
IND_ATIVO char
CONSTRAINT FK_ESTOQUEPRODUTO FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTOS(ID));


CREATE TABLE VENDAS(
ID int PRIMARY KEY NOT NULL,
USUARIO_ID int,
DAT_CRIACAO date,
DAT_ALTERACAO date, 
DAT_EXCLUSAO date,
CRIADO_POR_USU_ID int,
ALTERADO_POR_USU_ID int,
EXCLUIDO_POR_USU_ID int ,
IND_ATIVO char,
CONSTRAINT FK_VENDAUSUARIO FOREIGN KEY (USUARIO_ID)
REFERENCES USUARIO(ID));

CREATE TABLE VENDAS_PRODUTOS(
ID int PRIMARY KEY NOT NULL,
ID_VENDA int,
ID_PRODUTO int,
USUARIO_ID int,
VALOR decimal,
DESCONTO decimal,
VALOR_FINAL decimal,
DAT_CRIACAO date,
DAT_ALTERACAO date,
DAT_EXCLUSAO date,
CRIADO_POR_USU_ID int,
ALTERADO_POR_USU_ID int,
EXCLUIDO_POR_USU_ID int,
IND_ATIVO char,
CONSTRAINT FK_VENDASPRODUTO_USUARIO FOREIGN KEY (USUARIO_ID)
REFERENCES USUARIO(ID),
CONSTRAINT FK_VENDA_VENDASPRODUTO FOREIGN KEY (ID_VENDA)
REFERENCES VENDAS(ID),
CONSTRAINT FK_VENDA_PRODUTO FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTOS(ID));






